services:
  # --- NUEVO SERVICIO: BALANCEADOR DE CARGA ---
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Ahora entramos por el puerto 80 (estándar web)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - uce-net

  # SERVICIO 1: APLICACIÓN WEB (Modificado para escalar)
  web:
    build: ./app # ./app ya que esta dentro de la carpeta app
    # ports:
    #   - "5000:5000"  <-- COMENTADO: Ya no exponemos este puerto al mundo
    expose:
      - "5000" # Solo visible para Nginx dentro de la red
    environment:
      - DATABASE_URL=postgresql://uce_user:secret_password@postgres:5432/ucedb
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - postgres
      - mongo
    networks:
      - uce-net

  # SERVICIO 2: POSTGRESQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: uce_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: ucedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uce-net

  # SERVICIO 3: MONGODB
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    networks:
      - uce-net

# VOLÚMENES PERSISTENTES
volumes:
  postgres_data:
  mongo_data:

# REDES
networks:
  uce-net:
